package com.redhat.gerenciamento;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Destinatario implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Destinatario() {
    }

}