package com.redhat.gerenciamento;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Destinatario implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String destinatarioEmail;
   private java.lang.Boolean chamadaWebservice;

   public Destinatario()
   {
   }

   public java.lang.String getDestinatarioEmail()
   {
      return this.destinatarioEmail;
   }

   public void setDestinatarioEmail(java.lang.String destinatarioEmail)
   {
      this.destinatarioEmail = destinatarioEmail;
   }

   public java.lang.Boolean getChamadaWebservice()
   {
      return this.chamadaWebservice;
   }

   public void setChamadaWebservice(java.lang.Boolean chamadaWebservice)
   {
      this.chamadaWebservice = chamadaWebservice;
   }

   public Destinatario(java.lang.String destinatarioEmail,
         java.lang.Boolean chamadaWebservice)
   {
      this.destinatarioEmail = destinatarioEmail;
      this.chamadaWebservice = chamadaWebservice;
   }

}