package com.redhat.gerenciamento;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Documentacao implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String nomeDoProjeto;
   private java.lang.String breveDescricao;

   public Documentacao()
   {
   }

   public java.lang.String getNomeDoProjeto()
   {
      return this.nomeDoProjeto;
   }

   public void setNomeDoProjeto(java.lang.String nomeDoProjeto)
   {
      this.nomeDoProjeto = nomeDoProjeto;
   }

   public java.lang.String getBreveDescricao()
   {
      return this.breveDescricao;
   }

   public void setBreveDescricao(java.lang.String breveDescricao)
   {
      this.breveDescricao = breveDescricao;
   }

   public Documentacao(java.lang.String nomeDoProjeto,
         java.lang.String breveDescricao)
   {
      this.nomeDoProjeto = nomeDoProjeto;
      this.breveDescricao = breveDescricao;
   }

}